version: 1.0.0
spring:
  datasource:
    name: mysql-datasource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      register-mbeans: true
      pool-name: hikari-pool
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/datahub_db_executor?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: '{cipher}6d7a6184efc2a28a9c7e7b31ca462a8099b3a637607fd68262cb44dc99388f69'
      password: '{cipher}1033b1da3eee0e66e254fd8560df4d81f2f69b8d75cce4befb3d756d0d4ec088'
      
# jobs
job:
  block:
    threads: 100 # 处理分块最大线程数
    max: 10 # 最大块数 
    maxIndexNotExist: 1 # 没有索引时最大块数
    records: 10000 # 每块记录数
    cacheSize: 10 # 缓存量大小, 单位兆(M)
    progressPeriodSeconds: 10 # 汇报进度周期, 单位秒(s)

# table lock
lock: 
  table:
    timeoutSeconds: 300
  record:
    timeoutSeconds: 300
    
# hystrix 必须加否则无效(默认false)
feign: 
  hystrix:
    enabled: true
    
hystrix:
  command:
    datahub-db-executor:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            interruptOnTimeout: true
            timeoutInMilliseconds: 5000
            
datahub-db-executor:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    
# management
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
        
# mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.shersfy.datahub.dbexecutor.model
  
# logging
logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'
